### ISSUE TITLE
(BUG) {Thermostats in 2.3.1} 

### ISSUE THREAD

**Issue by adavison007** [tonesto7/homebridge-smartthings-v2#100]
## Verify the following before opening an trouble issue

**Go over all the following points, and put an `x` in all the boxes that apply.
If you're unsure about any of these, don't hesitate to ask. We're here to help!**

-  [x] That _OAuth_ is Enabled for the SmartApp under the IDE.
-  [x] The SmartApp and Device Handler are using the latest code available.
-  [x] That Both the SmartApps and Device Handlers have been _Published for You_ in the IDE.

---
## About Your Setup
I have 2.3.1 installed for Smart App and Homebridge

## Expected Behavior
Thermostats appear in homekit from smart things if they are selected as "Other Device" in smart app. 

If I remove them from other device and add them as either heating only or standard thermostat, they do not appear....

If I remove them from Thermostat and add them back in as "other Device" they work

**Comment by tonesto7** [comment]
I can confirm this.
I'm working on a way to validate a thermostat device has the required capabilities/attributes. 
I need to build out a list of attributes to translate   It's going to take me some time though.

**Comment by HammerAce42** [comment]
Will the resolution to this also address #19?

**Comment by tonesto7** [comment]
@adavison007  I was able to determine the cause of defining the device types manually not working (I can't guarantee that just by adding a thermostat to the tstat input will make it work), but it's a start.

I've just pushed out v2.3.2 of SmartApp and Plugin

**Comment by adavison007** [comment]
Thanks, I’ll take a look and let you know

Adam Davison
adavison@me.com
07748 761448

Sent from my iPhone

> On 24 Feb 2020, at 20:13, tonesto7 <notifications@github.com> wrote:
> 

﻿
@adavison007 I was able to determine the cause of defining the device types manually not working (I can't guarantee that just by adding a thermostat to the tstat input will make it work), but it's a start.

I've just pushed out v2.3.2 of SmartApp and Plugin

**Comment by adavison007** [comment]
@tonesto7 Thanks for the hard work, I updated the home bridge and smart app.. I have managed to add the thermostat under specific device type "Heat Only" Thermostat... that worked... Unfortunaltey it still shows a heat range in auto.? I didn't;t try normal thermostat, I presumed that one would have the range? let me know.

Thanks again

![IMG_1274](https://user-images.githubusercontent.com/47482260/75192407-120a0900-574c-11ea-83b6-72e9b190aeaf.png)

**Comment by tonesto7** [comment]
yea, I was afraid of this. I didn't have time to work on these non-standard thermostats.

**Comment by tonesto7** [comment]
Please post the output of the device data viewer in the smartapp. 

Just select the thermostat and copy the JSON output into this issue

**Comment by adavison007** [comment]
> Please post the output of the device data viewer in the smartapp.
> 
> Just select the thermostat and copy the JSON output into this issue

@tonesto7 here is a normal Tado wall thermostat

**Comment by adavison007** [comment]
@tonesto7 here is a Tado radiator value thermostat

**Comment by adavison007** [comment]
@tonesto7 modes = Home, Away or manual.

I’d love home to be auto (sets temp for that time of day from settings) Away (sets temp for away mode) manual = heat

**Comment by tonesto7** [comment]
@adavison007  So I think I sorted out the issue with it showing auto and cool from on the thermostat when you select a heat-only device.

I'm really nervous about trying to support all these custom thermostats.  I'm a nightmare to maintain once you step outside the capability standards of the platform.
I'm not saying no just that I need to think about it.

For the time being update your smartapp and open it and press done.  
It should remove the auto/cool characteristics for now.

**Comment by adavison007** [comment]
> @adavison007 So I think I sorted out the issue with it showing auto and cool from on the thermostat when you select a heat-only device.
> 
> I'm really nervous about trying to support all these custom thermostats. I'm a nightmare to maintain once you step outside the capability standards of the platform.
> I'm not saying no just that I need to think about it.
> 
> For the time being update your smartapp and open it and press done.
> It should remove the auto/cool characteristics for now.

@tonesto big thanks for looking into this, I updated the smart app, still shows as 2.3.2 and have rebooted homebridge, heat and auto still remain....see attactched

![IMG_1284](https://user-images.githubusercontent.com/47482260/75382616-b7e78000-58d2-11ea-9c75-989a256f7b60.png)

**Comment by adavison007** [comment]
@tonesto7 will you be supporting thermostat mode only... European customers don't have cool and heat on same thermostats, we just need heat on and off, no need for the range...
